blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from blog.feeds import AllPostsRssFeed

from users import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    
    #注册
    url(r'^users/', include('users.urls')),
    
    #登录、注销
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),\

    #重置密码
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    
    #修改密码
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),    
        
    url(r'^$', views.index, name='index'),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'^search/', include('haystack.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
]

templates/base.html
{% load staticfiles %}

{% load blog_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}苍云横渡{% endblock %}</title>

    <link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}" />
    <link rel="bookmark" href="{% static 'blog/img/favicon.ico' %}" type="image/x-icon"　/>
    
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="baidu-site-verification" content="2TeA0dJ76r" />

    <!-- css -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/friendly.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/themes/image.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pagination.css' %}">
    
    {% block stylesheet %}
    {% endblock stylesheet%}

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="https://cdn.bootcss.com/scrollup/2.4.1/jquery.scrollUp.js"></script>
    <script>
    $(function () {
        $.scrollUp({
            scrollName: 'scrollUp', // Element ID
            topDistance: '300', // Distance from top before showing element (px)
            topSpeed: 300, // Speed back to top (ms)
            animation: 'fade', // Fade, slide, none
            animationInSpeed: 200, // Animation in speed (ms)
            animationOutSpeed: 200, // Animation out speed (ms)
            scrollText: '', // Text for element
            activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
        });
    });
    </script>
    <script>
    $(function(){     
        var cubuk_seviye = $(document).scrollTop();  
        var header_yuksekligi = $('.navbar').outerHeight();  
        $(window).scroll(function() {  
            var kaydirma_cubugu = $(document).scrollTop();  
  
            if (kaydirma_cubugu > header_yuksekligi){$('.navbar').addClass('gizle');}   
            else {$('.navbar').removeClass('gizle');}  
  
            if (kaydirma_cubugu > cubuk_seviye){$('.navbar').removeClass('sabit'); $('.navbar-collapse').removeClass('in');}   
            else {$('.navbar').addClass('sabit');}                  
  
            cubuk_seviye = $(document).scrollTop();   
        });  
    });  
    </script>
    <script type="text/javascript">   
    $(function() {
        var $sidebar   = $("#float"),   
            $window    = $(window),   
            offset     = $sidebar.offset(),   
            topPadding = 100; 
            documentHeight = $(document).height();
  
        $window.scroll(function() {
            var sideBarHeight = $sidebar.height();
            if ($window.scrollTop() > offset.top) {
                var newPosition = $window.scrollTop() - offset.top + topPadding
                var maxPosition = documentHeight - (sideBarHeight + 1184.5);
                if (newPosition > maxPosition) {
                    newPosition = maxPosition;
                }
                $sidebar.stop().animate({   
                    marginTop: newPosition
                });   
            } else {   
                $sidebar.stop().animate({   
                    marginTop: 0   
                });   
            }   
        });   
    }); 
    </script>
    <script>
    (function(){
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        }
        else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
    </script>
   
    <!-- Daovoice -->
    <script>(function(i,s,o,g,r,a,m){i["DaoVoiceObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;a.charset="utf-8";m.parentNode.insertBefore(a,m)})(window,document,"script",('https:' == document.location.protocol ? 'https:' : 'http:') + "//widget.daovoice.io/widget/15ff98e5.js","daovoice")</script>
    
    <style type="text/css">     
    .fixed{position:fixed; top:20px; width:250px;}
        h4 {
            margin-top: 20px;
            margin-bottom: 10px;
        }
    
        #scrollUp {
            margin-bottom: 60px;
            margin-right: 5.5px;
        }
    
        blockquote {
            font-size: 16px;
            background-color: #f2f2f2
        }
     
        code {
            background-color: #f2f2f2;
            color: #000;
            }
        ul {
            font-weight: 400;
            }
    
        .codehilite {
            font-weight: 400;
            }
        
        .gizle {  
            top: -90px;  
            }  
        .sabit {  
            top:0;  
            z-index: 9999;  
            } 
        
        .entry-content {
            font-size: 16px;
            line-height: 1.5;
            font-weight: 300;
            color: #000;
            }
        .entry-title {
            font-size: 22px;
            margin-bottom: 15px;
            padding: 5px 20px 0;
            }
        .entry-meta {
            margin-bottom: 15px;
            }
            
        .divider_new {
            height: 1px;
            margin: 5px 0;
            overflow: hidden;
            background-color: #e5e5e5;
            }
        
        hr { margin-top:10px; margin-bottom:10px;}
        .widget{ 
            padding: 10px 15px;
            padding-top: 0;
            box-shadow: 0 3px 3px 0 rgba(0, 0, 0, 0.05);
            margin-bottom: 35px;
            }
        .widget-title {
            margin-bottom:0;
            padding: 15px 0 0;
            }  
        .widget-tag-cloud {
            padding-top: 10px;
            }
        .widget-tag-cloud ul li {
            margin-top:4px;
            }
        .widget-content ul ul {
            margin-top: 0px;
            }    
        .widget-content ul li {
            margin-bottom: 0px;
            }
        
        .post {
            padding: 15px 30px 0;
            margin-bottom: 35px;
            box-shadow: 0 3px 3px 0 rgba(0, 0, 0, 0.05); 
            }
        .post-body{ 
            font-size: 16px; 
            line-height: 1.7;
            }
        .post-body a{ 
            color: #337ab7;
            text-decoration: none; 
            }
            
        .jumbotron {
            background-color:#f9f9f9;
            }
        body { 
            padding-top: 80px; 
            background-color: #f9f9f9;
            }
        .content-body {
            margin-top:0px;
            }
        .fixed {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 40px;
            z-index: 99;
            }
        
        .logo { 
            margin-top: -2.5px;
            width: 64px;
            height: 28.4px;
            }
        .logo img {
            width: 100%;
            height: 100%;
            }
            
        .invalid-feedback {
            color: red;
            }
        
        .navbar {
            transition: top .3s;
            }
            
        span.highlighted {
            color: red;
            }
    </style>
    
</head>

<body>
<!-- 【顶部导航条】 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- 【适应小窗口浏览】 -->
        <div class="navbar-header">
            <button type="button" style="margin-top:18px;" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
      
            <!-- 【logo】 -->
            <a class="navbar-brand" href="{% url 'blog:index' %}">
                <div class="logo">
                    <img alt="Brand" src="{% static 'blog/img/logo1.png' %}">
                </div>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="https://blog.csdn.net/qq_35554125">博客</a></li>
                <li><a href="https://www.jianshu.com/u/b4a8325dcfee">简书</a></li>
                <li><a href="https://github.com/laiyuancai/cloudcrossing">Github</a></li>
        
                <!-- 【下拉菜单按钮】 -->
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a></li>
                            <li role="separator" class="divider_new"></li>
                            <li><a href="{% url 'logout' %}?next={% url 'blog:index' %}">注销登录</a></li>
                        </ul>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">登录</a></li>
                    <li><a href="{% url 'users:register' %}">注册</a></li>
                {% endif %}
                    </li>
            </ul>
      
            <!-- 【搜索】 -->
            <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'haystack_search' %}">
                <div class="form-group">
                    <input type="search" class="form-control" name="q" placeholder="搜索" required>
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
        </div>    <!-- /.navbar-collapse -->
    </div>    <!-- /.container-fluid -->
</nav>

<div class="content-body">
    <div class="container">     
        {% block head %}
        {% endblock head %}
        <div class="row">
            {% block row %}
            {% endblock row %}
        </div>
    </div>
</div>

<script>
daovoice('init', {
  app_id: "15ff98e5",
  user_id: "{{ current_user.user_id }}", // 必填: 该用户在您系统上的唯一ID
  email: "{{ current_user.email }}", // 选填:  该用户在您系统上的主邮箱
  name: "{{ current_user.name }}", // 选填: 用户名
  signed_up: {{ current_user.signed_up }} // 选填: 用户的注册时间，用Unix时间戳表示
});
daovoice('update');
</script>

<script>
daovoice('init', {
  app_id: "15ff98e5"
});
daovoice('update');
</script>

<!-- 【脚注】 -->
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"></script>
                <p class="copyright">
                    &copy 2018 苍云横渡 <a href="http://www.miibeian.gov.cn"; target=_blank>粤ICP备18038030号-1 </a>
                    <a href="http://www.miibeian.gov.cn"; target=_blank>粤ICP备18038030号-2 </a>
                    <a href="https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44130302100149"; target=_blank>
                    粤公网安备44130302100149 <img src="http://mat1.gtimg.com/www/images/qq2012/icon_yuewangga1.png" width="16" height="16"></a>
                    <img src="{% static 'blog/img/cat.png' %}" style="width: 100%; height: 100%; width:16.57px; height: 16.42px;">
                    <i class="fa fa-user-md"></i><span id="busuanzi_container_site_pv">
                        本站访客数:<span id="busuanzi_value_site_pv"></span>
                    </span>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- 【Mobile Menu】 -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="https://blog.csdn.net/qq_35554125">博客</a></li>
            <li><a href="https://www.jianshu.com/u/b4a8325dcfee">简书</a></li>
            <li><a href="https://github.com/laiyuancai/cloudcrossing">Github</a></li>
            <li><a href="about.html">关于</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}登录{% endblock %}

{% block row %}
  <div class="container">
    <h2 class="text-center my-4">
      <a href="#"><strong>登 录</strong></a>
    </h2>
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-4 col-sm-4 col-md-offset-4 col-lg-offset-4 col-sm-offset-4">
        <div class="card">
          <div class="card-body">
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">登录</button>
            </form>
          </div>
          <p> </p>
          <div class="card-footer text-muted text-center">
            没有账号？<a href="{% url 'users:register' %}">立即注册</a>
          </div>
        </div>
        <p> </p>
        <div class="text-center py-2">
          <small>
            <a href="{% url 'password_reset' %}">忘记密码？</a>
          </small>
        </div>
      </div>
    </div>
  </div>
  <p> </p>
{% endblock row%}

templates/password_change.html
{% extends 'base.html' %}

{% load blog_tags %}

{% block title %}修改密码{% endblock %}

{% block row %}
  <div class="row">
    <h2 class="text-center my-4">
      <a href="#">修改密码</a>
    </h2>
    <div class="col-lg-4 col-md-4 col-sm-4 col-md-offset-4 col-lg-offset-4 col-sm-offset-4">
      <form class="form" action="{% url 'password_change' %}" method="post">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">确认修改</button>
      </form>
    </div>
  </div>
  <p> </p>
{% endblock row %}

templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}修改密码成功{% endblock %}

{% block row %}
  <div class="alert alert-success text-center" role="alert">
    <strong>修改成功!</strong> 请记住新密码哦~
  </div>
  <div class="text-center">
    <a href="{% url 'index' %}" class="btn btn-primary round">返回首页</a>
  </div>
  <p> </p>
{% endblock row %}

templates/password_reset.html
{% extends 'base.html' %}

{% load static %}

{% block title %}重置密码{% endblock %}

{% block row %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-4 col-sm-4 col-md-offset-4 col-lg-offset-4 col-sm-offset-4">
      <h2 class="text-center my-4">
        <a href="#"><strong>重置密码</strong></a>
      </h2>
      <div class="card">
        <div class="card-body">
          <p>请输入您的邮箱地址，我们将会发送一个的链接到您的邮箱来重置您的密码。</p>
          <form action="{% url 'password_reset' %}" method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">提交</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <p> </p>
{% endblock row %}

templates/password_reset_complete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}新密码设置成功！{% endblock %}

{% block row %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-4 col-sm-4 col-md-offset-4 col-lg-offset-4 col-sm-offset-4">
      <div class="card">
        <div class="card-body">
          <h2 class="text-center my-4">
            <a href="#"><strong>新密码设置成功</strong></a>
          </h2>
          <div class="alert alert-success text-center" role="alert">
            你的口令己经设置。现在你可以继续进行登录。
          </div>
          <a href="{% url 'login' %}" class="btn btn-primary btn-block">返回登录</a>
        </div>
      </div>
    </div>
  </div>
  <p> </p>
{% endblock row %}

templates/password_reset_confirm.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  {% if validlink %}
    {{ form.user.username }} 修改密码
  {% else %}
    重置密码
  {% endif %}
{% endblock title%}

{% block row %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-4 col-sm-4 col-md-offset-4 col-lg-offset-4 col-sm-offset-4">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h2 class="text-center my-4">
              <a href="#"><strong>{{ form.user.username }} 重置密码</strong></a>
            </h2>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">提交</button>
            </form>
          {% else %}
            <h2 class="text-center my-4">
              <a href="#"><strong>重置密码</strong></a>
            </h2>
            <div class="alert alert-danger text-center" role="alert">
              您的重置密码链接已失效，请重新尝试
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-primary btn-block">重新发送密码重置链接</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <p> </p>
{% endblock row%}

templates/password_reset_done.html
{% extends 'base.html' %}

{% load static %}

{% block title %}邮件已发送{% endblock %}

{% block row %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-4 col-sm-4 col-md-offset-4 col-lg-offset-4 col-sm-offset-4">
      <h2 class="text-center my-4">
        <a href="#"><strong>密码重置链接已经发送</strong></a>
      </h2>
      <div class="card">
        <div class="card-body">
          <div class="alert alert-success" role="alert">
          <p>如果您输入的邮件地址所对应的账户存在，设置密码的提示已经发送邮件给您，您将很快收到。</p>
          <p>
              如果你没有收到邮件, 请确保您所输入的地址是正确的, 并检查您的垃圾邮件文件夹.
          </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock row%}

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your cloudcrossing username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The cloudcrossing Team